### ISSUE TITLE
Build failure: SteamLeaderboard_t conversion ambiguous

### ISSUE THREAD

**Issue by jandrewlong** [Kermer/GodotSteam#10]
I am unable to build, as best I can tell, this is the error message:

```
modules/godotsteam/godotsteam.cpp:286:70: error: conversion from 'SteamLeaderboard_t {aka long long unsigned int}' to 'const Variant' is ambiguous
    Ref<SteamLeaderboard> sLeaderboard( callData->m_hSteamLeaderboard );
```

I'm using scons on Linux, with stable 2.1 version of Godot, in your leaderboards branch.

I get the same error trying to build the latest git version of Godot

**Comment by Kermer** [comment]
It still compiles fine on Windows with 2.1stable.
Sadly I still haven't installed any Linux yet.

You can try to cast that SteamLeaderboard_t to int first, but can't tell if it'll work.
(On line 286 of godotsteam.cpp):
`Ref<SteamLeaderboard> sLeaderboard( (int)(callData->m_hSteamLeaderboard) );`

**Comment by jandrewlong** [comment]
Casting as int fixed that problem, now I've got this:

```
modules/godotsteam/godotsteam_leaderboard.cpp:63:48: error: no matching function for call to 'operator new [](sizetype, const char [85])'
  CSteamID *pUsers = memnew(CSteamID[users_count]);
                                                ^
core/os/memory.h:250:109: note: in definition of macro 'memnew'
 #define memnew(m_class) _post_initialize(new(__FILE__ ":" __STR(__LINE__) ", memnew type: " __STR(m_class)) m_class)
                                                                                                             ^
modules/godotsteam/godotsteam_leaderboard.cpp:63:48: note: candidate is:
  CSteamID *pUsers = memnew(CSteamID[users_count]);
                                                ^
core/os/memory.h:250:109: note: in definition of macro 'memnew'
 #define memnew(m_class) _post_initialize(new(__FILE__ ":" __STR(__LINE__) ", memnew type: " __STR(m_class)) m_class)
                                                                                                             ^
<built-in>: note: void* operator new [](long unsigned int)
<built-in>: note:   candidate expects 1 argument, 2 provided

```

**Comment by Kermer** [comment]
In above commit: fixed the previous, "ambiguous", error and changed the memnew/memdelete to the basic new/delete.
Please test if it works now.

**Comment by jandrewlong** [comment]
It builds successfully now.
